input_type: "http_stream" # Either "http_stream" or "file_stream"

file_stream:
  path: ""

http_stream:
  url: "http://192.168.0.171:8080/?action=stream"
  publish_image: true
  width: 480
  height: 640
  mmpp: 0.0887
  roi_x0: 70
  roi_y0: 120
  roi_x1: 345
  roi_y1: 390

depth:
  enable: false
  topic_name: "depth"
  compute_type: "cuda" # Either 'cuda' or 'cpu'
  model_path: $(find gelsight_ros)/data/nnr15.pt

markers:
  enable: true
  topic_name: "markers"
  publish_image: true
  threshold_block_size: 11
  threshold_neg_bias: 15
  marker_neighborhood_size: 20

flow:
  enable: true
  topic_name: "flow"
  publish_image: false
  n: 0
  m: 0 
  x0: 0
  y0: 0
  dx: 0
  dy: 0

pose:
  enable: false
  topic_name: "pose"
  method: "depth" # Either 'markers' or 'depth'
  rolling_avg: 1 # Must be 1 or greater
