cam_url: "http://192.168.0.170:8080/?action=stream"

nn_compute: "cuda"
nn_output_size:
  width: 120
  height: 160
nn_mmpp: 0.0887

pca_buffer_size: 10
gaussian_kernel:
  width: 0
  height: 0

publish_markers: true
n_markers: 10
m_markers: 15

depth_thresh:
  type: "exponential"
  gaussian:
    max: 10.0
    min: 2.0
    sig: 150.0
  exponential:
    max: 10.0
    min: 0.1
    beta: 0.2
