http_stream:
  url: "http://192.168.0.171:8080/?action=stream"
  topic_name: "/raw" 
  height: 160
  width: 120
  mmpp: 0.1896
  roi: [[114, 147], [388, 132], [134, 476], [358, 476]]

diff:
  enable: true
  topic_name: "diff"

depth:
  enable: false
  topic_name: "depth"
  method: "model" # Either 'functional' or 'model'
  compute_type: "cuda" # Either 'cuda' or 'cpu'
  model_path: $(find gelsight_ros)/data/nnr15.pt

markers:
  enable: true
  topic_name: "markers"
  publish_image: true
  threshold_block_size: 31
  threshold_neg_bias: 19
  marker_neighborhood_size: 24

flow:
  enable: true
  topic_name: "flow"
  publish_image: true
  n: 10
  m: 14
  x0: 13
  y0: 6
  dx: 11
  dy: 11

pose:
  enable: false
  topic_name: "pose"
  method: "depth" # Either 'markers' or 'depth'
  rolling_avg: 1 # Must be 1 or greater
