nn_compute: "cuda"
nn_output_size:
  width: 120
  height: 160
nn_mmpp: 0.0887

pca_buffer_size: 4
gaussian_kernel:
  width: 0
  height: 0

publish_markers: false
n_markers: 10
m_markers: 14

depth_thresh:
  type: "none"
  gaussian:
    max: 10.0
    min: 2.0
    sig: 150.0
  exponential:
    max: 10.0
    min: 0.1
    beta: 0.2
